version: "3.9"

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: thuusbezorgd-rabbitmq-node
    volumes:
      - ./development/rabbitmq/data/:/var/lib/rabbitmq/

  postgres:
    build: development/database
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_USER=postgres
      - DB_APP_PASS=postgres
      - STOCK_DATABASE_NAME=stock
      - ORDERS_DATABASE_NAME=orders
      - DELIVERY_DATABASE_NAME=delivery
    volumes:
      - "./data:/var/data/database"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@hu.nl
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e!
